### ISSUE TITLE
2022 Update Issues

### ISSUE THREAD

**Issue by CoolBudy1** [SwerveDriveSpecialties/swerve-lib#10]
I've been working to update all of our software to 2022, and according to some people, the jitpack.io hasnt been updated yet, and it causing this error. `********** Robot program starting **********
Unhandled exception instantiating robot jdk.internal.loader.BuiltinClassLoader java.lang.ClassNotFoundException: edu.wpi.first.wpiutil.RuntimeLoader
Error at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source): Unhandled exception instantiating robot jdk.internal.loader.BuiltinClassLoader java.lang.ClassNotFoundException: edu.wpi.first.wpiutil.RuntimeLoader
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
at com.revrobotics.jni.RevJNIWrapper.<clinit>(RevJNIWrapper.java:42)
at com.revrobotics.CANSparkMaxLowLevel.<clinit>(CANSparkMaxLowLevel.java:38)
at frc.robot.Constants.<clinit>(Constants.java:69)
at frc.robot.subsystems.Shooter.<init>(Shooter.java:13)
at frc.robot.Robot.<clinit>(Robot.java:24)
at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:322)
at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:463)
at frc.robot.Main.main(Main.java:23)
The robot program quit unexpectedly. This is usually due to a code error.
The above stacktrace can help determine where the error occurred.
See https://wpilib.org/stacktrace for more information.
Error at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:336): The robot program quit unexpectedly. This is usually due to a code error.
The above stacktrace can help determine where the error occurred.
See https://wpilib.org/stacktrace for more information.
Could not instantiate robot jdk.internal.loader.BuiltinClassLoader!
Error at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:342): Could not instantiate robot jdk.internal.loader.BuiltinClassLoader!` I am not sure what to do.

**Comment by brennenputh** [comment]
I have also been having this issue.  It makes it look like REVLib's fault, which is incredibly confusing.  Is there any timeline for these changes being published on jitpack?

**Comment by democat3457** [comment]
Have y'all tried the 1.1.0 update from a couple days ago

`'com.github.SwerveDriveSpecialties:swerve-lib:1.1.0'`
